// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBD3AhIaIPUokjASkO50uyZEfnsng9oles',
    appId: '1:548588515842:web:fe61fd5406b704372aad1b',
    messagingSenderId: '548588515842',
    projectId: 'proyekambw-9249g',
    authDomain: 'proyekambw-9249g.firebaseapp.com',
    storageBucket: 'proyekambw-9249g.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAGz4FpgJty65iIoH2T1_P0XW9z-uoKfCA',
    appId: '1:548588515842:android:46675c6df18088c22aad1b',
    messagingSenderId: '548588515842',
    projectId: 'proyekambw-9249g',
    storageBucket: 'proyekambw-9249g.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA-RO57g1ayvUJGm-Mrl_ZMhETCs0mMVTM',
    appId: '1:548588515842:ios:681b64dff22925582aad1b',
    messagingSenderId: '548588515842',
    projectId: 'proyekambw-9249g',
    storageBucket: 'proyekambw-9249g.firebasestorage.app',
    iosBundleId: 'id.or.alkitab.caua.musa',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA-RO57g1ayvUJGm-Mrl_ZMhETCs0mMVTM',
    appId: '1:548588515842:ios:10b3979d454324bf2aad1b',
    messagingSenderId: '548588515842',
    projectId: 'proyekambw-9249g',
    storageBucket: 'proyekambw-9249g.firebasestorage.app',
    iosBundleId: 'com.example.loginPageMusa',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBD3AhIaIPUokjASkO50uyZEfnsng9oles',
    appId: '1:548588515842:web:03363c21d7b310d82aad1b',
    messagingSenderId: '548588515842',
    projectId: 'proyekambw-9249g',
    authDomain: 'proyekambw-9249g.firebaseapp.com',
    storageBucket: 'proyekambw-9249g.firebasestorage.app',
  );
}
