// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC1JSp1atPwqsP5r09vyL8uR8CVAwoaWB8',
    appId: '1:31931433644:web:9831be1d3a05167b42d509',
    messagingSenderId: '31931433644',
    projectId: 'loginpagemusa',
    authDomain: 'loginpagemusa.firebaseapp.com',
    storageBucket: 'loginpagemusa.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBRgRgCExqPTAYHoD3LDV1aPCHEtQkHQQ4',
    appId: '1:31931433644:android:94cd4c48393a57b442d509',
    messagingSenderId: '31931433644',
    projectId: 'loginpagemusa',
    storageBucket: 'loginpagemusa.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD_biPUa5Pr6HwucXOX40b2_Hw9njXkaYc',
    appId: '1:31931433644:ios:3f6ef61718eac9eb42d509',
    messagingSenderId: '31931433644',
    projectId: 'loginpagemusa',
    storageBucket: 'loginpageymusa.firebasestorage.app',
    iosClientId: '31931433644-rrl72ug2j24tgj33o29o8roceoqvcskl.apps.googleusercontent.com',
    iosBundleId: 'com.example.loginPageMusa',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD_biPUa5Pr6HwucXOX40b2_Hw9njXkaYc',
    appId: '1:31931433644:ios:3f6ef61718eac9eb42d509',
    messagingSenderId: '31931433644',
    projectId: 'loginpagemusa',
    storageBucket: 'loginpagemusa.firebasestorage.app',
    iosClientId: '31931433644-rrl72ug2j24tgj33o29o8roceoqvcskl.apps.googleusercontent.com',
    iosBundleId: 'com.example.loginPageMusa',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC1JSp1atPwqsP5r09vyL8uR8CVAwoaWB8',
    appId: '1:31931433644:web:ce34a256aeac48cb42d509',
    messagingSenderId: '31931433644',
    projectId: 'loginpagemusa',
    authDomain: 'loginpagemusa.firebaseapp.com',
    storageBucket: 'loginpagemusa.firebasestorage.app',
  );

}